// Generated by CoffeeScript 1.3.3
(function() {
  var api, file, http, site;

  http = require('http');

  file = require('node-static');

  api = require('./api/thesaurus.js');

  site = new file.Server('./app');

  http.createServer(function(request, response) {
    return request.addListener('end', function() {
      if (request.url.indexOf('/thesaurus') === -1) {
        return site.serve(request, response);
      } else {
        if (request.method === 'GET') {
          return api.handleWordQuery(request, response);
        } else if (request.method === 'POST') {
          return api.handleWordUpdate(request, response);
        }
      }
    });
  }).listen(8080);

}).call(this);
